### ISSUE TITLE
Define the Data Structure

### ISSUE THREAD

**Issue by dermutzh** [SS20-SE2-Monopoly-Team/monopoly#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

- Define the Data Structure of the different Objects our Game will have. E.g. Player (name, money, streets, houses, cards the player can keep for a while - like "Get out of Jail Card"..); Cards (title, description, etc.) Streets, etc.
- Define how we will handle the Gameboard.
- Choose a Pattern. (MVC only, MVVM only, or the combination of them)
- Construct the Flow of a Game, so we can assure everyone is speaking of the same, and that we only have one source of truth. 
- Evaluate the advantages when using libGDX as the game engine or if it is easier to make it all by ourselves.

**Additional context**
Defining this in advance, will make our life much easier.
See: https://libgdx.badlogicgames.com/index.html for more Infos about libGDX.

**Comment by valentingavran** [comment]
Create UML diagram

**Comment by valentingavran** [comment]
Since there will be more complex connections and relations between the objects, we might consider using Room. Under these links, you can find more information about what Room is. I don't think it is much more additional work, because we save all the accessing methods and much time on testing.

https://codelabs.developers.google.com/codelabs/android-room-with-a-view/#0
https://developer.android.com/topic/libraries/architecture/room

**Comment by dermutzh** [comment]
Update: libGDX --> cancelled. too much effort. 

Data Structure is mostly defined. (UML diagram + rough Flow of Game)

Regarding Room: checked it out, looks good. This needs to be made in another Issue, when Database starts getting relevant.

This Issue only focuses on bringing the Classes up and running for further development.
