### ISSUE TITLE
In-app Data Initializer

### ISSUE THREAD

**Issue by valentingavran** [SS20-SE2-Monopoly-Team/monopoly#25]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Write handler from where we can fetch the data, so we have one unique Flow.
Real-world-data like Streets/Cards will be entered in another issue.
(Use data from Strings.xml)
**Additional context**

**Comment by dermutzh** [comment]
This Issue will be changed:

Last time I worked with Android was in 2014, back then they didn't have any solution for fetching Assets. This changed due to the fast paced development of Android. Now they offer a good flow for accessing our Icons and In-App-Strings. Therefore this Issue will not cover the creation of a Handler, instead this Issue covers an Initializer for the Data. 

Main reason for the Initializer: Work as fast as possible with "real-data" AND prepare it in the beginning for multi-language. (or AT/DE Version of the Game, etc)
